### ISSUE TITLE
BOP biomes refuse to generate. Old version works fine.

### ISSUE THREAD

**Issue by MagmaSlime123** [juraj-hrivnak/RTGUnofficial#7] opened 2022-09-01 04:02 UTC
##### Affected Mod Versions:
![image](https://user-images.githubusercontent.com/51277766/187829015-28d095cb-e900-43c6-ba51-fb7139c55cf5.png)
- Forge version: 2860.

##### Issue Description:
Title.

##### Steps to reproduce the issue: (If it's easily reproducible.)
Load a world.

##### Extra Information:
N/A. Logs have nothing related to any of this.

**Comment by juraj-hrivnak** [comment] 2022-09-04 10:54
Script? I can't reproduce it

**Comment by MagmaSlime123** [comment] 2022-09-04 18:18
I'm using the default configs. Never touched anything.

Edit: I looked in this "etc" folder you have on this repo, and I have no idea what it does. Tried placing the BOP and RTG folders it has into the scripts folder, and they don't function at all. Sorry for being an absolute idiot. BOP support for RTG shouldn't require this much effort. ProjectVibrantJourneys is just plug-and-play, and works just fine.

**Comment by juraj-hrivnak** [comment] 2022-09-05 17:08
You need to follow this guide on the RTG wiki:
https://github.com/Team-RTG/Realistic-Terrain-Generation/wiki/BiomeTweaker-configuration

I'm closing this as this is a user-end issue.

**Closed as completed by juraj-hrivnak** 2022-09-05 17:08 UTC
Labels: bug, user-end issue

**Comment by MagmaSlime123** [comment] 2022-09-05 17:22
Again, where do I place these folders at. I tried within the BT folder, and in BT's scripts folder.
BOP biomes refuse to generate still.

![image](https://user-images.githubusercontent.com/51277766/188494873-3fd7ecb0-5669-46ec-8ab9-310717173b91.png)

**Comment by juraj-hrivnak** [comment] 2022-09-05 17:29
Put the [`RTG.cfg`](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/1.12-master/etc/biometweaker/BiomesOPlenty/RTG.cfg)  in the scripts folder, and that's it.
